// Code generated by Fern. DO NOT EDIT.

package client

import (
	http "net/http"
	core "sdk/core"
	internal "sdk/internal"
	option "sdk/option"
	sandbox "sdk/sandbox"
)

type Client struct {
	Sandbox *sandbox.Client

	baseURL string
	caller  *internal.Caller
	header  http.Header
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		Sandbox: sandbox.NewClient(opts...),
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
		header: options.ToHeader(),
	}
}
