// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	core "sdk/core"
)

type SandboxError struct {
	*core.APIError
	Body string
}

func (s *SandboxError) UnmarshalJSON(data []byte) error {
	var body string
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	s.StatusCode = 404
	s.Body = body
	return nil
}

func (s *SandboxError) MarshalJSON() ([]byte, error) {
	return json.Marshal(s.Body)
}

func (s *SandboxError) Unwrap() error {
	return s.APIError
}
