// Code generated by Fern. DO NOT EDIT.

package sandbox

import (
	context "context"
	http "net/http"
	sdk "sdk"
	core "sdk/core"
	internal "sdk/internal"
	option "sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	baseURL string
	caller  *internal.Caller
	header  http.Header
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		WithRawResponse: NewRawClient(options),
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
		header: options.ToHeader(),
	}
}

// Example post request
func (c *Client) SimplePost(
	ctx context.Context,
	request *sdk.SimplePostRequestBody,
	opts ...option.RequestOption,
) (*sdk.SimplePostResponse, error) {
	response, err := c.WithRawResponse.SimplePost(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example get request
func (c *Client) SimpleGet(
	ctx context.Context,
	opts ...option.RequestOption,
) (*sdk.SimpleGetResponse, error) {
	response, err := c.WithRawResponse.SimpleGet(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example post request with optional fields
func (c *Client) OptionalExamplesPost(
	ctx context.Context,
	request *sdk.OptionalExamplesPostRequestBody,
	opts ...option.RequestOption,
) (*sdk.OptionalExamplesPostResponse, error) {
	response, err := c.WithRawResponse.OptionalExamplesPost(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
